name = "red_onion"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2022-09-10"
account_id = "7d672dd84ded6250fcfbb962ac9b51b5"
#route = "<mainly useful when you want to setup custom domains (optional too)>"
[site]
bucket = ".output/public"